### Create user
POST localhost:9000/users/002
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@acme.com"
}

### update email - same email error
PUT localhost:9000/users/001/change-email
Content-Type: application/json

{
  "email": "john@acme.com"
}


### update email
PUT localhost:9000/users/001/change-email
Content-Type: application/json

{
  "email": "john.doe@acme.com"
}